api_platform:
    title: 'API SymfonyProjet'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        json:     ['application/json']
        #jsonld:   ['application/ld+json']
        xml:      ['application/xml']
        html:     ['text/html']
    collection:
        pagination:
            client_items_per_page: true
            items_per_page: 4

